# question_data = [
#     {"text": "A slug's blood is green.", "answer": "True"},
#     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
#     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
#     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
#     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
#              "you are free to take it home to eat.", "answer": "True"},
#     {"text": "In London, UK, if you happen to die in the House of Parliament, "
#              "you are entitled to a state funeral.", "answer": "False"},
#     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
#     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
#     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
#     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
#     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
#     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# ]

question_data = {"response_code": 0,
                  "results":
                      [{"type": "boolean",
                        "difficulty": "easy",
                        "category": "Geography",
                        "question": "Rhode Island is actually located on the US mainland, despite its name.",
                        "correct_answer": "True", "incorrect_answers": ["False"]},
                       {"type": "boolean",
                        "difficulty": "medium",
                        "category": "Geography",
                        "question": "The title of the 1969 film &quot;Krakatoa, East_of Java&quot; is incorrect, as Krakatoa is in fact west of Java.",
                        "correct_answer": "True",
                        "incorrect_answers": ["False"]},
                       {"type": "boolean", "difficulty": "medium",
                        "category": "Entertainment: Japanese Anime &amp; Manga",
                        "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
                        "correct_answer": "True", "incorrect_answers": ["False"]},
                       {"type": "boolean", "difficulty": "easy", "category": "Sports",
                        "question": "In association football, or soccer, a corner kick is when the game restarts after someone scores a goal.",
                        "correct_answer": "False", "incorrect_answers": ["True"]},
                       {"type": "boolean", "difficulty": "easy", "category": "Animals",
                        "question": "Rabbits are rodents.", "correct_answer": "False",
                        "incorrect_answers": ["True"]},
                       {"type": "boolean", "difficulty": "medium",
                        "category": "Science &amp; Nature",
                        "question": "The Doppler effect applies to light.",
                        "correct_answer": "True", "incorrect_answers": ["False"]},
                       {"type": "boolean", "difficulty": "easy", "category": "Geography",
                        "question": "California is larger than Japan.",
                        "correct_answer": "True", "incorrect_answers": ["False"]},
                       {"type": "boolean", "difficulty": "medium",
                        "category": "General Knowledge",
                        "question": "The scientific name for the Southern Lights is Aurora Australis?",
                        "correct_answer": "True", "incorrect_answers": ["False"]},
                       {"type": "boolean", "difficulty": "medium", "category": "Vehicles",
                        "question": "Arriva is owned by the Deutsche Bahn.",
                        "correct_answer": "True", "incorrect_answers": ["False"]},
                       {"type": "boolean", "difficulty": "easy",
                        "category": "Entertainment: Video Games",
                        "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
                        "correct_answer": "True", "incorrect_answers": ["False"]}]}


